"""empty message

Revision ID: 48908a211c9f
Revises: 0fcea1a6152c
Create Date: 2023-11-28 22:03:45.186270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48908a211c9f'
down_revision = '0fcea1a6152c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categories_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tags_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'categories', ['categories_id'], ['id'])
        batch_op.create_foreign_key(None, 'tags', ['tags_id'], ['id'])
        batch_op.drop_column('tags')
        batch_op.drop_column('categories')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categories', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tags', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tags_id')
        batch_op.drop_column('categories_id')

    op.drop_table('tags')
    op.drop_table('categories')
    # ### end Alembic commands ###
