"""empty message

Revision ID: 677d039933f1
Revises: 0ef3b0a51df3
Create Date: 2023-11-22 18:23:03.193737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677d039933f1'
down_revision = '0ef3b0a51df3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('countries_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'countries', ['countries_id'], ['id'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('countries_id')
        batch_op.drop_column('name')

    op.drop_table('countries')
    # ### end Alembic commands ###
